//Storing the birth months of individuals and printing them
let person1= Math.floor(Math.random()*12)+1;
let person2= Math.floor(Math.random()*12)+1;
let person3= Math.floor(Math.random()*12)+1;
let person4= Math.floor(Math.random()*12)+1;
let person5= Math.floor(Math.random()*12)+1;
let person6= Math.floor(Math.random()*12)+1;
let person7= Math.floor(Math.random()*12)+1;
let person8= Math.floor(Math.random()*12)+1;
let person9= Math.floor(Math.random()*12)+1;
let person10= Math.floor(Math.random()*12)+1;
let person11= Math.floor(Math.random()*12)+1;
let person12= Math.floor(Math.random()*12)+1;
let person13= Math.floor(Math.random()*12)+1;
let person14= Math.floor(Math.random()*12)+1;
let person15= Math.floor(Math.random()*12)+1;
let person16= Math.floor(Math.random()*12)+1;
let person17= Math.floor(Math.random()*12)+1;
let person18= Math.floor(Math.random()*12)+1;
let person19= Math.floor(Math.random()*12)+1;
let person20= Math.floor(Math.random()*12)+1;
let birthMonthMap = new Map();
let Jan= new Array();
let Feb= new Array();
let Mar= new Array();
let Apr= new Array();
let May= new Array();
let Jun= new Array();
let Jul= new Array();
let Aug= new Array();
let Sep= new Array();
let Oct= new Array();
let Nov= new Array();
let Dec = new Array();
let Persons =[person1,person2,person3,person4,person5,person6,person7,person8,person9,person10,person11,person12,person13,person14,person15,person16,person16.person17,person18,person19,person20]; 
Persons.forEach(element => {
    switch(element){
        case 1: Jan.push(element);
        break;
        case 2: Feb.push(element);
        break;
        case 3: Mar.push(element);
        break;
        case 4: Apr.push(element);
        break;
        case 5: May.push(element);
        break;
        case 6: Jun.push(element);
        break;
        case 7: Jul.push(element);
        break;
        case 8: Aug.push(element);
        break;
        case 9: Sep.push(element);
        break;
        case 10: Oct.push(element);
        break;
        case 11: Nov.push(element);
        break;
        case 12: Dec.push(element);
        break;
        default: break;
    }
});
birthMonthMap.set("January",Jan.length);
birthMonthMap.set("February",Feb.length);
birthMonthMap.set("March",Mar.length);
birthMonthMap.set("Aril",Apr.length);
birthMonthMap.set("May",May.length);
birthMonthMap.set("June",Jul.length);
birthMonthMap.set("July",Jul.length);
birthMonthMap.set("August",Aug.length);
birthMonthMap.set("September",Sep.length);
birthMonthMap.set("October",Oct.length);
birthMonthMap.set("November",Nov.length);
birthMonthMap.set("December",Dec.length);
for(let [key,value] of birthMonthMap.entries()){
    console.log(key+" -> "+value+" no. of people");
}